### ISSUE TITLE
Doors & Trapdoors cause infinite error logs - performance issue

### ISSUE THREAD

**Issue by EnchantedBread** [PandaMods-Dev/Pandas-Extra-Details#48]
Whenever loading any door or trapdoor an infinite string of errors are generated in the logs:

Can't find mesh at extra_details:pandalib/meshes/block/door/trap_door.json
Can't find mesh at extra_details:pandalib/meshes/block/door/door.json

doesn't affect gameplay in any major way, however, performance does take a slight hit the longer logs don't get cleared

also noticed that when looking at doors a see-through outline appears which doesn't appear on other blocks so may be related

[modlist.txt](https://github.com/PandaDap2006/Pandas-Extra-Details/files/15245479/modlist.txt)

**Comment by Katranune** [comment]
Duplicate of #47

**Comment by ThePandaOliver** [comment]
Closing as duplicate
